 name: Sonar Scan
 on:
   push:
     branches:
       - master
 jobs:
   sonarcloud:
     name: SonarCloud Scan and Quality Gate
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: SonarCloud Scaning Process
       uses: SonarSource/sonarcloud-github-action@v1.3
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         
     - name: Wait for Quality Gate Approval
       id: quality-gate
       uses: peaceiris/actions-approval@v2
       with:
         message: 'Please review the SonarCloud Quality Gate report'
         reviewers: "<Abhi-Moreyeahs>" 
         
     - name: Check Quality Gate Status
       if: steps.quality-gate.outputs.approved == 'true'
       run: echo 'Quality Gate passed!' 

