 name: Sonar Scan
 on:
   push:
     branches:
       - master
   pull_request:
    types: [opened, synchronize, reopened]
    
 jobs:
   sonarcloud:
     name: SonarCloud Scan and Quality Gate
     runs-on: ubuntu-latest
     
     steps:
     - uses: actions/checkout@v2
       with:
          fetch-depth: 0

     - name: SonarCloud Scaning Process
       uses: SonarSource/sonarcloud-github-action@v1.3
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         
   approval:
     runs-on: ubuntu-latest
     
     steps:    
      - name: Review request
        uses: trstringer/manual-approval@v1
        with:
            secret: ${{ secrets.SONAR_TOKEN }}
            approvers: Abhi-Moreyeahs  
            minimum-approvals: 1
            issue-title: "Sonar CLoud Scanning Process"
            issue-body: "Please approve or deny the Sccaned Quality gate"
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: 'Accepted'
            additional-denied-words: 'Rejected'
            


