 name: Sonar Scan
 on:
   push:
     branches:
       - master
   pull_request:
    types: [opened, synchronize, reopened]
    
 jobs:
   sonarcloud:
     name: SonarCloud Scan and Quality Gate
     runs-on: ubuntu-latest
     
     steps:
     - uses: actions/checkout@v2
       with:
          fetch-depth: 0

     - name: SonarCloud Scaning Process
       uses: SonarSource/sonarcloud-github-action@master
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         
   approval:
     runs-on: ubuntu-latest
     
     steps:    
      - name: Request approval
        uses: trstringer/manual-approval@v1
        with:
          github-token: ${{ secrets.GT_TOKEN }}
          reviewers: Abhi-Moreyeahs, drashinkar
          team-reviewers: Abhi-Moreyeahs, drashinkar
          message: Please review the code changes and approve or request changes.     
          additional-approved-words: 'Accepted'
          additional-denied-words: 'Rejected'
            


