name: Snyk Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Snyk
        run: npm install -g snyk
      - name: Snyk scan
        run: snyk auth $secrets.SNYK_TOKEN && snyk test
      - name: node module updations
        run: npm install
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}